app/Http/routes.php
<?php
Route::post('/send', 'MailController@send');

routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* View Composer*/
View::composer(['*'], function($view){
    $user = Auth::user();
    $view->with('user', $user);
});
Route::get('sys/logout', function () { return view('logout'); });

//....Routes for new prelogin layouts
Route::get('/fp', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.welcome')); })->name('preLogin.welcome');
Route::get('/privacy-policy', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.privacyPolicy')); })->name('prelogin.privacyPolicy');
Route::get('/terms-conditions', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.termsConditions')); })->name('prelogin.termsConditions');
Route::get('/fsbo', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.fbso.saleByOwner')); })->name('preLogin.fsbo');
Route::get('/mls', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.mls.mlsListingService')); })->name('preLogin.mls');
Route::get('/transaction-coordinator', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.agents.agents')); })->name('preLogin.agents');
Route::get('/about', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.about')); })->name('preLogin.about');
Route::get('/offers', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.offers')); })->name('preLogin.offers');
Route::get('/brands', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.brands')); })->name('preLogin.brands');
Route::get('/offer-assistant', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.offerAssistant.officeAssistant')); })->name('preLogin.offerAssistant');
Route::match(['get', 'post'], '/membership', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.register1')); })->name('prelogin.membership');
Route::post('/request-membership', 'InvitationController@saveMemberRequest')->name('prelogin.requestMembership');
Route::get('/fsbo/get-started', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.fbso.fsboGetStarted')); })->name('preLogin.fsbo.get-started');
Route::get('/mls/get-started', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.mls.mlsGetStarted')); })->name('preLogin.mls.get-started');
Route::get('/agent/get-started', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.agents.agentGetStarted')); })->name('preLogin.agents.get-started');
Route::get('/transaction-coordinator/get-started', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.agents.agentGetStarted')); })->name('preLogin.tc.get-started');

// ... Press Releases
Route::get('/press-release/1',
    function () { return \Illuminate\Support\Facades\Redirect::to( asset('press') . '/20180413-transaction_coordinator_service.pdf');})->name('press.1');
Route::get('/press-release/2',
    function () { return \Illuminate\Support\Facades\Redirect::to( asset('press') . '/20180515-transaction_timeline.pdf');})->name('press.2');
Route::get('/press-release/3',
    function () { return \Illuminate\Support\Facades\Redirect::to( asset('press') . '/20180713-hire_of_leading_transaction_coordinator.pdf');})->name('press.3');


// ... Contact Us
//
Route::get('/otc/contact/{nameFirst?}/{nameLast?}/{email?}/{phone?}/{role?}','MailController@contactUs')->name('email.contactUs');

// ... Notifications
//
Route::get('/alert','MailController@sendReminderEmails')->name('email.alert');
Route::post('/shared/document/email', 'MailController@documentSharedEmail')->name('documentSharedEmail');

Route::get('/get_offer_image/{offerID}/{offerType}/{image}',
    function ($offerID, $offerType, $image)
    {
        $path = public_path("_uploaded_documents/offers/$offerID/$offerType/$image");
        return file_exists($path) ? response(file_get_contents($path))->header('Content-Type', 'image') : abort(404);
    });

Route::resource('agents', 'AgentController');

Route::get('/home', 'DashboardController@prosumerDashboard')->name('user.dashboard');
Route::get('/', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.welcome')); })->name('home');
Route::get('/welcome', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.welcome')); })->name('prelogin');
Route::get('/contactUs', function () { return view(\App\Library\Utilities\_LaravelTools::addVersionToViewName('prelogin.contactUs')); })->name('prelogin.contactUs');
Route::post('/contactUs/submit', 'HomeController@submitContactUs')->name('submitContactRequest');

Route::post('/ta/status/', 'TransactionController@updateStatus')->name('transaction.updateStatus');
Route::post('/ta/overrideaddress/', 'TransactionController@override')->name('override.address');

//...........Invoice development ............
Route::get('/invoices/{userID?}', 'InvoiceController@getInvoicesByUserID')->name('invoices.byUserID');
Route::get('/invoice/{invoiceID?}', 'InvoiceController@inputInvoice')->name('invoice.input');
Route::get('/invoice/update/status/{invoiceID?}', 'InvoiceController@updateInvoiceStatus')->name('update.InvoiceStatus');
Route::post('/saveInvoice','InvoiceController@saveInvoice')->name('saveInvoice');
Route::post('/invoices/search','InvoiceController@searchInvoice')->name('search.Invoice');
Route::match(['get', 'post'],'/PrintInvoice/{invoiceID}','InvoiceController@PrintInvoice')->name('PrintInvoice');
//................... Offers ..........................................................................
Route::post('/offer/check', 'OfferController@checkProperty')->name('offer.checkProperty');
Route::get('/offer/{offerID?}', 'OfferController@inputOffer')->name('input.Offer');
Route::get('/transaction/offers/{tcID?}', 'OfferController@getOfferByTCID')->name('offers.byTC');
Route::post('/offer/save', 'OfferController@saveOffer')->name('save.Offer');
Route::post('/offer/upload', 'OfferController@uploadDocument')->name('offer.uploadDocument');
Route::post('/offer/upload-offer', 'OfferController@uploadOffer')->name('offer.uploadOffer');
Route::post('/offer/upload-counter-offer', 'OfferController@uploadCounterOffer')->name('offer.uploadCounterOffer');
Route::get ('/offer', 'OfferController@index');


Route::get('/userProfile', 'UserController@saveProfile')->name('userProfile');
Route::post('/userProfile', 'UserController@saveProfile');
Route::post('/uploadImage', 'UserController@uploadImage')->name('userProfile.uploadImage');

/*** Alerts *****/
Route::post('/alerts/mark/read', 'AlertController@markAlertsAsRead')->name('markAlertsAsRead');
Route::post('/alerts/clear', 'AlertController@clearAllAlerts')->name('clearAllAlerts');

Route::get('/transaction', 'TransactionController@index')->name('transaction.index');
Route::get('/transaction/create/{side}', 'TransactionController@create')->name('transaction.create');
Route::get('/transaction/owned/{ajax?}/{userID?}', 'TransactionController@getOwnedTransactions')->name('getOwnedTransactions');

// ... routes for Dashboard
Route::get('/dash/ta/list/{role?}/{userID?}', 'DashboardController@transactionListByUser')->name('dash.ta.list');
//Route::get('/dashboard/questions/{taID}', 'DashboardController@questionList')->name('dashboard.questions');
//Route::get('/dashboard/uid/{userID}', 'DashboardController@transactionList')->name('dashboard.uid');
Route::get('/source/side/{transactionID}/{source}/{ajax?}', 'TransactionController@isSameSide')->name('isSameSide');
Route::get('/dashboard', 'DashboardController@prosumerDashboard')->name('dashboard');

// ... Input Role Data

Route::get('/ta/b/{transactionID?}/{buyerID?}', 'TransactionController@inputBuyer')->name('inputBuyer');
Route::get('/ta/s/{transactionID?}/{sellerID?}', 'TransactionController@inputSeller')->name('inputSeller');
Route::get('/ta/ba/{transactionID?}/{buyersAgentID?}', 'TransactionController@inputBuyerAgent')->name('inputBuyerAgent');
Route::get('/ta/sa/{transactionID?}/{sellerAgentID?}', 'TransactionController@inputSellerAgent')->name('inputSellerAgent');
Route::get('/ta/btc/{transactionID?}/{ajax?}/{tcType?}', 'TransactionController@inputBuyerTC')->name('inputBuyerTC');
Route::get('/ta/stc/{transactionID?}/{ajax?}/{tcType?}', 'TransactionController@inputSellerTC')->name('inputSellerTC');

Route::get('/ta/br/{transactionID?}', 'TransactionController@inputBroker')->name('inputBroker');
Route::get('/ta/e/{transactionID?}', 'TransactionController@inputEscrow')->name('inputEscrow');
Route::get('/ta/t/{transactionID?}', 'TransactionController@inputTitle')->name('inputTitle');
Route::get('/ta/l/{transactionID?}', 'TransactionController@inputLoan')->name('inputLoan');
Route::get('/ta/p/{transactionID?}', 'TransactionController@inputProperty')->name('inputProperty');
Route::get('/ta/d/{transactionID?}', 'TransactionController@inputDetails')->name('inputDetails');
Route::get('/ta/share/{transactionID?}', function () { return view('2a.transaction.rooms.share'); })->name('share');

// ... Save Role Data
Route::match(['get', 'post'],'/ta/save/getNavBuyer',  'TransactionController@getNavBuyer')->name('getNavBuyer');

app/Models/Agent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Agent extends Model_Parent
{
    use SoftDeletes;
    public $table = 'Agents';

    const CREATED_AT = 'DateCreated';
    const UPDATED_AT = 'DateUpdated';

    const TYPE_BUYER = 'b';
    const TYPE_SELLER = 's';
    const TYPE_BOTH = 'bs';

    const EMAIL_FORMAT_HTML = 'html';
    const EMAIL_FORMAT_TEXT = 'text';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['DateCreated', 'DateUpdated', 'deleted_at',];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $autoUpsert = [
        'DateCreated', 'DateUpdated',
    ];
}

resources/views/agent/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="mc-wrapper">
		<div class="mc-heading">
			@if (!empty($_action))
                @if ($_action == 'saved')
                    <h2><i class="fa fa-user-circle"></i> Saved!</h2>
                @endif
            @endif
            <h1>
                @if ($_screenMode??null == 'create')
                    Create New
                @elseif ($_screenMode??null == 'edit')
                    Edit
                @else
                    View
                @endif
                {{ $_role['display'] }}
            </h1>
		</div>

		<!-- Show errors if they exist -->
        @if($errors->any())
			<div class="alert alert-danger alert-dismissable text-center">
				<a href="#" class="close" data-dismiss="alert" alert-label="close">&times;</a>
				There was an error submitting your form. Kindly review the errors below and resubmit your form
			</div>
        @endif

        <!-- Create new agent form -->
        <div class="mc-box-groups user new">
        	<form action="{{ route('agents.store') }}" method="POST">
        		{{ csrf_field() }}
        		{{--
					<input type="hidden" name="Transactions_ID" value="{{ (!empty($data['Transactions_ID']) ? $data['Transactions_ID'] : '') }}">
                <input type="hidden" name="Users_ID" value="{{ (!empty($data['Users_ID']) ? $data['Users_ID'] : '') }}">
				<input type="hidden" name="ID" value="{{ (!empty($data['ID']) ? $data['ID'] : '') }}">
        		 --}}
        		<div class="col-width-2">
        		 	<div class="mc-box">
        		 		<div class="mc-box-heading no-other">
        		 			<h2><i class="far fa-user"></i> PERSONAL DETAILS</h2>
        		 			<div class="clearfix"></div>
        		 		</div>
        		 		<div class="form-groups">
        		 			<div class="form-group{{ $errors->has('NameFirst') ? ' has-error' : '' }} with-label">
        		 				<label for="NameFirst" class="label-control">First Name <span class="important">*</span></label>
        		 				<input type="text" name="NameFirst" class="form-control first-name" placeholder="First Name" value="{{ old('NameFirst') }}">
        		 				@if($errors->has('NameFirst'))
									<span class="help-block">
										<strong>{{ $errors->first('NameFirst') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('NameLast') ? ' has-error' : '' }} with-label">
        		 				<label for="NameLast" class="label-control">Last Name <span class="important">*</span></label>
        		 				<input type="text" name="NameLast" class="form-control last-name" placeholder="Last Name" value="{{ old('NameLast') }}">
        		 				@if($errors->has('NameLast'))
									<span class="help-block">
										<strong>{{ $errors->first('NameLast') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('NameFull') ? ' has-error' : '' }} with-label">
								<label for="NameFull" class="label-control">Name on Document <span class="important">*</span></label>
								<input type="text" name="NameFull" class="form-control full-name" placeholder="NameFull" value="{{ old('NameFull') }}">
								@if($errors->has('NameFull'))
									<span class="help-block">
										<strong>{{ $errors->first('NameFull') }}</strong>
									</span>
								@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('Brokers_ID') ? ' has-error' : '' }} with-label">
        		 				<label for="Brokers_ID" class="label-control">Broker <span class="important">*</span></label>
        		 				<select name="Brokers_ID" id="" class="form-control">
        		 					{{--
										@foreach($brokers as $broker)
											<option value="{{ $broker->id }}">{{ $broker->id }}</option>
										@endforeach
        		 					 --}}
        		 					<option value="" disabled selected>Select Broker</option>
        		 					<option value="1">Broker 1</option>
        		 					<option value="2">Broker 2</option>
        		 				</select>
        		 				@if($errors->has('Brokers_ID'))
									<span class="help-block">
										<strong>{{ $errors->first('Brokers_ID') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('StateLicense') ? ' has-error' : '' }} with-label">
        		 				<label for="StateLicense" class="label-control">State License <span class="important">*</span></label>
        		 				<input type="text" class="form-control full-name" name="StateLicense" placeholder="State License" value="{{ old('StateLicense') }}">
        		 				@if($errors->has('StateLicense'))
									<span class="help-block">
										<strong>{{ $errors->first('StateLicense') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 		</div>
        		 	</div>

        		 	<div class="mc-box">
        		 		<div class="mc-box-heading no-other">
        		 			<h2><i class="far fa-comments"></i> CONTACT DETAILS</h2>
        		 			<div class="clearfix"></div>
        		 		</div>
        		 		<div class="form-groups">
        		 			<div class="form-group{{ $errors->has('PrimaryPhone') ? ' has-error' : '' }} with-label">
        		 				<label for="PrimaryPhone" class="label-control">Primary Phone <span class="important">*</span></label>
        		 				<input type="text" name="PrimaryPhone" class="form-control masked-phone" value="{{ old('PrimaryPhone') }}" placeholder="(###) ###-#####">
        		 				@if($errors->has('PrimaryPhone'))
									<span class="help-block">
										<strong>{{ $errors->first('PrimaryPhone') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('SecondaryPhone') ? ' has-error' : '' }} with-label">
        		 				<label for="SecondaryPhone" class="label-control">Secondary Phone <span class="important">*</span></label>
        		 				<input type="text" name="SecondaryPhone" class="form-control masked-phone" value="{{ old('SeconadryPhone') }}" placeholder="(###) ###-#####">
        		 				@if($errors->has('SecondaryPhone'))
									<span class="help-block">
										<strong>{{ $errors->first('SecondaryPhone') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('Email') ? ' has-error' : '' }} with-label">
        		 				<label for="Email" class="label-control">Email <span class="important">*</span></label>
        		 				<input type="email" name="Email" class="form-control" placeholder="Email" value="{{ old('Email') }}">
        		 				@if($errors->has('Email'))
									<span class="help-block">
										<strong>{{ $errors->first('Email') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('EmailFormat') ? ' has-error' : '' }} with-label">
        		 				<label for="EmailFormat" class="label-control">Email Format <span class="important">*</span></label>
                                <label class="checkbox">
                                	<input type="radio" name="EmailFormat" class="form-control" value="html" checked>
                                	<span>HTML</span>
                                </label>
                                <label class="checkbox">
                                	<input type="radio" name="EmailFormat" class="form-control" value="text">
                                	<span>Text</span>
                                </label>
                                @if($errors->has('EmailFormat'))
									<span class="help-block">
										<strong>{{ $errors->first('EmailFormat') }}</strong>
									</span>
                                @endif
        		 			</div>
        		 			<div class="form-group{{ $errors->has('ContactSMS') ? ' has-error' : '' }} with-label">
        		 				<label for="ContactSMS" class="label-control">Send Texts To</label>
        		 				<input type="text" class="form-control masked-phone" placeholder="(###) ###-#####" value="{{ old('ContactSMS') }}">
        		 				@if($errors->has('ContactSMS'))
									<span class="help-block">
										<strong>{{ $errors->first('ContactSMS') }}</strong>
									</span>
        		 				@endif
        		 			</div>
        		 		</div>
        		 	</div>
        		</div>
        		<div class="col-width-2">
        			<div class="mc-box">
        				<div class="mc-box-heading no-other">
	        				<h2><i class="fas fa-home"></i> ADDRESS</h2>
	        				<div class="clearfix"></div>
	        			</div>
	        			<div class="form-groups">
	        				<div class="form-group{{ $errors->has('Street1') ? ' has-error' : '' }} with-label">
	        					<label for="Street1" class="label-control">Street 1 <span class="important">*</span></label>
	        					<input type="text" class="form-control" name="Street1" value="{{ old('Street1') }}" placeholder="Street 1">
	        					@if($errors->has('Street1'))
									<span class="help-block">
										<strong>{{ $errors->first('Street1') }}</strong>
									</span>
	        					@endif
	        				</div>
	        				<div class="form-group{{ $errors->has('Street2') ? ' has-error' : '' }} with-label">
	        					<label for="Street2" class="label-control">Street 2</label>
	        					<input type="text" class="form-control" name="Street2" value="{{ old('Street2') }}" placeholder="Street 2">
	        					@if($errors->has('Street2'))
									<span class="help-block">
										<strong>{{ $errors->first('Street2') }}</strong>
									</span>
	        					@endif
	        				</div>
	        				<div class="form-group{{ $errors->has('Unit') ? ' has-error' : '' }} with-label">
	        					<label for="Unit" class="label-control">Unit</label>
	        					<input type="text" class="form-control" name="Unit" value="{{ old('Unit') }}" placeholder="Unit">
	        					@if($errors->has('Unit'))
									<span class="help-block">
										<strong>{{ $errors->first('Unit') }}</strong>
									</span>
	        					@endif
	        				</div>
	        				<div class="form-group{{ $errors->has('City') ? ' has-error' : '' }} with-label">
	        					<label for="City" class="label-control">City <span class="important">*</span></label>
	        					<input type="text" class="form-control" name="City" placeholder="City" value="{{ old('City') }}">
	        					@if($errors->has('City'))
	        						<span class="help-block">
	        							<strong>{{ $errors->first('City') }}</strong>
	        						</span>
	        					@endif
	        				</div>
	        				<div class="form-group{{ $errors->has('State') ? ' has-error' : '' }} with-label">
	        					<label for="State" class="label-control">State <span class="important">*</span></label>
	        					<select name="State">
	        						{!! \App\Library\Utilities\FormElementHelpers::buildOptionListFromConstantArray($data['State']??'CA',Config::get('otc.states'), 'index', 'value') !!}
	        					</select>
	        					@if($errors->has('State'))
									<span class="help-block">
										<strong>{{ $errors->first('State') }}</strong>
									</span>
	        					@endif
	        				</div>
	        				<div class="form-group{{ $errors->has('Zip') ? ' has-error' : '' }} with-label">
	        					<label for="Zip" class="label-control">Zip <span class="important">*</span></label>
	        					<input type="text" class="form-control" name="Zip" placeholder="Zip Code" value="{{ old('Zip') }}">
	        					@if($errors->has('Zip'))
									<span class="help-block">
										<strong>{{ $errors->first('Zip') }}</strong>
									</span>
	        					@endif
	        				</div>
	        			</div>
        			</div>
                    <div class="mc-box">
                    	<div class="mc-box-heading no-other">
                    		<h2><i class="far fa-file-alt"></i> NOTES</h2>
                    		<div class="clearfix"></div>
                    	</div>
                    	<div class="form-groups">
                    		<div class="form-group no-label">
                    			<textarea name="Notes" class="form-control"></textarea>
                    		</div>
                    	</div>
                    </div>
        		</div>
                <div class="clearfix"></div>
                <div class="ctrls">
                	<button class="btn red">SAVE</button>
                </div>
        	</form>
        </div>
	</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.masked-phone').mask('(###)-000-0000');
        });
    </script>

@endsection